repos:
  - repo: local
    hooks:
      - id: autocorrect
        name: autocorrect
        entry: "./scripts/autocorrect.sh --fix"
        language: script
        verbose: true
        files: \.swift$
  - repo: local
    hooks:
      - id: linting
        name: linting
        entry: "./scripts/autocorrect.sh lint"
        language: script
        verbose: true
        files: \.swift$
