name: sdk-tests

on:
  #  workflow_dispatch:
  push:
    branches: [ task/github-actions-tests ]
    intputs:
      network:
        description: 'MobileCoin Network'
        required: true
        default: 'mobiledev'
        type: choice
        options:
          - 'mobiledev'
          - 'alpha'
          - 'testNet'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: GCP Service Account
        run: |
          echo '${{ secrets.GCP_SERVICE_KEY }}' > "service-key.json"

      - name: Set the Network
        env:
          NETWORK_UNDER_TEST: ${{ github.event.inputs.network }}
        run: echo 'SKIPPING SETTING NETWORK FOR NOW' 

      - name: Make Setup
        run: make setup

      - name: Provide Dev Credentials
        env:
          TEST_DEV_USER: ${{ secrets.DEV_NETWORK_AUTH_USERNAME}}
          TEST_DEV_PASSWORD: ${{ secrets.DEV_NETWORK_AUTH_PASSWORD}}
        run: |
          echo 'setting dev user and password'
          bundle exec pod keys set devNetworkAuthUsername ${TEST_DEV_USER}
          bundle exec pod keys set devNetworkAuthPassword ${TEST_DEV_PASSWORD}

      - name: Provide TestNet Mnemonics 
        env:
          TEST_NET_MNEMONICS: ${{ secrets.TEST_ACCOUNT_MNEMONICS_COMMA_SEPARATED }}
        run: |
          echo 'Providing TestNet Mnemonics'
          bundle exec pod keys set testNetTestAccountMnemonicsCommaSeparated "$TEST_NET_MNEMONICS"

      - name: Provide DevNet Mnemonics 
        env:
          DEV_NET_MNEMONICS: ${{ secrets.MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPARATED }}
        run: |
          echo 'Providing DevNet Mnemonics'
          bundle exec pod keys set testNetTestAccountMnemonicsCommaSeparated "$DEV_NET_MNEMONICS"

      - name: Make Lock 
        run: |
          echo 'Running make lock as a prerequisite for setting up credentials' 
          make lock 

      - name: Generate CocoaPods Keys
        run:
          echo 'Generating CocoaPods Keys'
          bundle exec pod keys generate

      - name: Build
        run: make 
